### ISSUE TITLE
Support for ViperX 300 robot arms

### ISSUE THREAD

**Issue by sirwart** [wuphilipp/gello_mechanical#1]
I’m attempting to replicate some of the ALOHA results but wanted to use a gello arm to save on cost. Do you have any plans to support the ViperX or pointers if I wanted to try to add support myself?

**Comment by wuphilipp** [comment]
I currently don't have plans to add support for the ViperX arm (as ALOHA already does this). However if you are interested in making a GELLO for the ViperX, I'm happy to help support and provide CAD of the existing GELLO arms. Please drop me an email if you are interested!
