### ISSUE TITLE
AR4 base STL file is empty

### ISSUE THREAD

**Issue by boyentenbi** [wuphilipp/gello_mechanical#11]
@adob , I know it's fairly simple, but the STL file for the base of your AR4 gello is empty, would you be able to upload it? :) 

Thanks,
Peter

**Comment by adob** [comment]
The base STL file (ar4/3dprint_parts/base.stl) should be a symbolic link to
../../ur5/base.STL. Is that not the case?

**Comment by boyentenbi** [comment]
Ah that's right, thanks for clarifying.
