### ISSUE TITLE
Support for xArm 6 series

### ISSUE THREAD

**Issue by kaku2000** [wuphilipp/gello_mechanical#2]
Hello，

I happend to have 2 xArms，but they‘re neither 7 or 5，they are 6 and 6 lite…

Is it possible to release hardware support for those？Or if not so difficult，may just tell me where to modificate  ，like the link length etc.. and do it myself.

Thank you

**Comment by wuphilipp** [comment]
The lite6 was added recently by https://github.com/hygradme
Hope this helps!
https://github.com/wuphilipp/gello_mechanical/tree/main/lite6
